language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

notifications:
  email:
    recipients:
      - travis@23-5.eu
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#radioaldebaran"
    on_success: always
    on_failure: always

install: "pip install -r knot/python/Pip-packages.txt"

# command to run tests
script: nosetests -v knot/python/Test.py 
script: nosetests -v server/python/Test.py

